language: python
python:
- '2.7'
services:
- mysql
install: 
- pip install -r requirements.txt
- pip install coveralls
before_script:
before_install:
- sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-fr
- mkdir /home/travis/build/ptitoliv/cineapp/tmp/
- mkdir -p /home/travis/build/ptitoliv/cineapp/migrations/versions
- mysql -e 'create database cineapp_ci;'
script:
- cd /home/travis/build/ptitoliv/cineapp/
- find /home/travis/build/ptitoliv/cineapp/
- vapid -g
- vapid --applicationServerKey
- KEY=`vapid --applicationServerKey |cut -d '=' -f2 |tr -d ' ' |head -n 1` &&  sed -i s/__NOTIFICATION_APPLICATION_KEY__/${KEY}/g /home/travis/build/ptitoliv/cineapp/configs/settings_test.cfg
- cat /home/travis/build/ptitoliv/cineapp/configs/settings_test.cfg
- python manage.py db upgrade
- python tests/unit_tests.py
- coverage run --omit=/home/travis/virtualenv/* tests/unit_tests.py
after_success:
- coveralls
