version: 2.1

orbs:
  python: circleci/python@4.0.0

jobs:
  build:
    docker:
    - image: cimg/mariadb:10.6
    executor:
      name: python/default
      tag: '3.11'
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
    