"""Create Index for Full Text Search

Revision ID: 2b951c30abd6
Revises: df83eb974d59
Create Date: 2025-07-05 15:45:40.104942

"""

# revision identifiers, used by Alembic.
revision = '2b951c30abd6'
down_revision = 'df83eb974d59'

from alembic import op
import sqlalchemy as sa
import cineapp.migration_types

from sqlalchemy.dialects import mysql

def upgrade():
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.create_index('idx_show_fulltext_search', ['name', 'original_name', 'director'], unique=False, mysql_prefix='FULLTEXT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_index('idx_show_fulltext_search', mysql_prefix='FULLTEXT')

    # ### end Alembic commands ###
