"""Define session_id as unique and index field on PushNotification table

Revision ID: 31a42956fb9e
Revises: b75f7c7164ca
Create Date: 2017-08-28 12:50:20.929313

"""

# revision identifiers, used by Alembic.
revision = '31a42956fb9e'
down_revision = 'b75f7c7164ca'

from alembic import op
import sqlalchemy as sa
import cineapp.migration_types



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_push_notifications_session_id'), 'push_notifications', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_notifications_session_id'), table_name='push_notifications')
    # ### end Alembic commands ###
