"""Extend overview field length

Revision ID: 9a145ba5b160
Revises: 80411a880b39
Create Date: 2026-07-18 11:09:00.838056

"""

# revision identifiers, used by Alembic.
revision = '9a145ba5b160'
down_revision = '80411a880b39'

from alembic import op
import sqlalchemy as sa
import cineapp.migration_types

from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.alter_column('overview',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Truncate overviews that are too long before shrinking the column,
    # otherwise the ALTER fails in strict mode (ERROR 1265 Data too long).
    op.execute("UPDATE shows SET overview = LEFT(overview, 2000) "
               "WHERE CHAR_LENGTH(overview) > 2000")
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.alter_column('overview',
               existing_type=sa.String(length=5000),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###
