"""FavoriteTypes add a weight for each category for optimized sort

Revision ID: b037baf33cfa
Revises: 31a42956fb9e
Create Date: 2017-08-30 18:00:31.438844

"""

# revision identifiers, used by Alembic.
revision = 'b037baf33cfa'
down_revision = '31a42956fb9e'

from alembic import op
import sqlalchemy as sa
import cineapp.migration_types



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_types', sa.Column('star_weight', sa.Integer(), nullable=True))
    conn = op.get_bind()
    res=conn.execute("UPDATE favorite_types SET star_weight=1 WHERE star_type=\"favorite_star\"")
    res=conn.execute("UPDATE favorite_types SET star_weight=2 WHERE star_type=\"homework_star\"")
    res=conn.execute("UPDATE favorite_types SET star_weight=3 WHERE star_type=\"mustsee_star\"")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_types', 'star_weight')
    # ### end Alembic commands ###
