"""Database Initialisation

Revision ID: bbda659bcd01
Revises: None
Create Date: 2017-07-06 23:20:24.068223

"""

# revision identifiers, used by Alembic.
revision = 'bbda659bcd01'
down_revision = None

from alembic import op
import sqlalchemy as sa
import cineapp.migration_types



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_types',
    sa.Column('star_type', sa.String(length=20), nullable=False),
    sa.Column('star_message', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('star_type'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('origins',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('types',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('notifications', cineapp.migration_types.JSONEncodedDict(length=255), nullable=False),
    sa.Column('graph_color', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avatar'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)

    # chat_messages: create table, then index, then FK
    op.create_table('chat_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('posted_when', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('message_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_index('user_id', 'chat_messages', ['user_id'], unique=False)
    op.create_foreign_key('chat_messages_ibfk_1', 'chat_messages', 'users', ['user_id'], ['id'])

    # movies: create table, then column-named indexes, then FKs, then explicit indexes
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=5), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.String(length=5), nullable=True),
    sa.Column('director', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('overview', sa.String(length=2000), nullable=True),
    sa.Column('tmvdb_id', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('added_when', sa.DateTime(), nullable=True),
    sa.Column('added_by_user', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmvdb_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_index('added_by_user', 'movies', ['added_by_user'], unique=False)
    op.create_foreign_key('movies_ibfk_1', 'movies', 'users', ['added_by_user'], ['id'])
    op.create_index('origin', 'movies', ['origin'], unique=False)
    op.create_foreign_key('movies_ibfk_2', 'movies', 'origins', ['origin'], ['id'])
    op.create_index('type', 'movies', ['type'], unique=False)
    op.create_foreign_key('movies_ibfk_3', 'movies', 'types', ['type'], ['id'])
    op.create_index(op.f('ix_movies_director'), 'movies', ['director'], unique=False)
    op.create_index(op.f('ix_movies_name'), 'movies', ['name'], unique=False)
    op.create_index(op.f('ix_movies_origin'), 'movies', ['origin'], unique=False)
    op.create_index(op.f('ix_movies_release_date'), 'movies', ['release_date'], unique=False)
    op.create_index(op.f('ix_movies_type'), 'movies', ['type'], unique=False)
    op.create_index(op.f('ix_movies_url'), 'movies', ['url'], unique=False)

    # favorite_movies: create table, then indexes, then FKs
    # movie_id is covered by PK (movie_id, user_id), no separate index needed
    op.create_table('favorite_movies',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('star_type', sa.String(length=100), nullable=True),
    sa.Column('added_when', sa.DateTime(), nullable=True),
    sa.Column('deleted_when', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('movie_id', 'user_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_index('star_type', 'favorite_movies', ['star_type'], unique=False)
    op.create_index('user_id', 'favorite_movies', ['user_id'], unique=False)
    op.create_foreign_key('favorite_movies_ibfk_1', 'favorite_movies', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key('favorite_movies_ibfk_2', 'favorite_movies', 'favorite_types', ['star_type'], ['star_type'])
    op.create_foreign_key('favorite_movies_ibfk_3', 'favorite_movies', 'users', ['user_id'], ['id'])

    # marks: create table, then indexes, then FKs
    # user_id is covered by PK (user_id, movie_id), no separate index needed
    op.create_table('marks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('seen_when', sa.Date(), nullable=True),
    sa.Column('seen_where', sa.String(length=4), nullable=True),
    sa.Column('mark', sa.Float(), nullable=True),
    sa.Column('updated_when', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('homework_when', sa.DateTime(), nullable=True),
    sa.Column('homework_who', sa.Integer(), server_default=sa.text(u'NULL'), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'movie_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_index('homework_who', 'marks', ['homework_who'], unique=False)
    op.create_foreign_key('marks_ibfk_1', 'marks', 'users', ['homework_who'], ['id'])
    op.create_index('movie_id', 'marks', ['movie_id'], unique=False)
    op.create_foreign_key('marks_ibfk_2', 'marks', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key('marks_ibfk_3', 'marks', 'users', ['user_id'], ['id'])

    # mark_comment: create table, then indexes, then FKs
    op.create_table('mark_comment',
    sa.Column('markcomment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mark_user_id', sa.Integer(), nullable=True),
    sa.Column('mark_movie_id', sa.Integer(), nullable=True),
    sa.Column('posted_when', sa.DateTime(), nullable=True),
    sa.Column('deleted_when', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('markcomment_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_index('mark_user_id', 'mark_comment', ['mark_user_id', 'mark_movie_id'], unique=False)
    op.create_foreign_key('mark_comment_ibfk_1', 'mark_comment', 'marks', ['mark_user_id', 'mark_movie_id'], ['user_id', 'movie_id'])
    op.create_index('user_id', 'mark_comment', ['user_id'], unique=False)
    op.create_foreign_key('mark_comment_ibfk_2', 'mark_comment', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mark_comment')
    op.drop_table('marks')
    op.drop_table('favorite_movies')
    op.drop_table('movies')
    op.drop_table('chat_messages')
    op.drop_table('users')
    op.drop_table('types')
    op.drop_table('origins')
    op.drop_table('favorite_types')
    # ### end Alembic commands ###
