"""Database Initialisation

Revision ID: bbda659bcd01
Revises: None
Create Date: 2017-07-06 23:20:24.068223

"""

# revision identifiers, used by Alembic.
revision = 'bbda659bcd01'
down_revision = None

from alembic import op
import sqlalchemy as sa
import cineapp.migration_types



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_types',
    sa.Column('star_type', sa.String(length=20), nullable=False),
    sa.Column('star_message', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('star_type'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('origins',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('types',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('notifications', cineapp.migration_types.JSONEncodedDict(length=255), nullable=False),
    sa.Column('graph_color', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avatar'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_table('chat_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('posted_when', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_messages_ibfk_1'),
    sa.PrimaryKeyConstraint('message_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=5), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.String(length=5), nullable=True),
    sa.Column('director', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('overview', sa.String(length=2000), nullable=True),
    sa.Column('tmvdb_id', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('added_when', sa.DateTime(), nullable=True),
    sa.Column('added_by_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_user'], ['users.id'], name='movies_ibfk_1'),
    sa.ForeignKeyConstraint(['origin'], ['origins.id'], name='movies_ibfk_2'),
    sa.ForeignKeyConstraint(['type'], ['types.id'], name='movies_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmvdb_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_index(op.f('ix_movies_director'), 'movies', ['director'], unique=False)
    op.create_index(op.f('ix_movies_name'), 'movies', ['name'], unique=False)
    op.create_index(op.f('ix_movies_origin'), 'movies', ['origin'], unique=False)
    op.create_index(op.f('ix_movies_release_date'), 'movies', ['release_date'], unique=False)
    op.create_index(op.f('ix_movies_type'), 'movies', ['type'], unique=False)
    op.create_index(op.f('ix_movies_url'), 'movies', ['url'], unique=False)
    op.create_table('favorite_movies',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('star_type', sa.String(length=100), nullable=True),
    sa.Column('added_when', sa.DateTime(), nullable=True),
    sa.Column('deleted_when', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='favorite_movies_ibfk_1'),
    sa.ForeignKeyConstraint(['star_type'], ['favorite_types.star_type'], name='favorite_movies_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorite_movies_ibfk_3'),
    sa.PrimaryKeyConstraint('movie_id', 'user_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('marks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('seen_when', sa.Date(), nullable=True),
    sa.Column('seen_where', sa.String(length=4), nullable=True),
    sa.Column('mark', sa.Float(), nullable=True),
    sa.Column('updated_when', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('homework_when', sa.DateTime(), nullable=True),
    sa.Column('homework_who', sa.Integer(), server_default=sa.text(u'NULL'), nullable=True),
    sa.ForeignKeyConstraint(['homework_who'], ['users.id'], name='marks_ibfk_1'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='marks_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='marks_ibfk_3'),
    sa.PrimaryKeyConstraint('user_id', 'movie_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('mark_comment',
    sa.Column('markcomment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mark_user_id', sa.Integer(), nullable=True),
    sa.Column('mark_movie_id', sa.Integer(), nullable=True),
    sa.Column('posted_when', sa.DateTime(), nullable=True),
    sa.Column('deleted_when', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['mark_user_id', 'mark_movie_id'], ['marks.user_id', 'marks.movie_id'], name='mark_comment_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='mark_comment_ibfk_2'),
    sa.PrimaryKeyConstraint('markcomment_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mark_comment')
    op.drop_table('marks')
    op.drop_table('favorite_movies')
    op.drop_table('movies')
    op.drop_table('chat_messages')
    op.drop_table('users')
    op.drop_table('types')
    op.drop_table('origins')
    op.drop_table('favorite_types')
    # ### end Alembic commands ###
