"""Add original_name field into movie table

Revision ID: ee38ddab5497
Revises: b8f94316eb0f
Create Date: 2017-08-21 11:48:34.012193

"""

# revision identifiers, used by Alembic.
revision = 'ee38ddab5497'
down_revision = 'b8f94316eb0f'

from alembic import op
import sqlalchemy as sa
import cineapp.migration_types



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('original_name', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_movies_original_name'), 'movies', ['original_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_original_name'), table_name='movies')
    op.drop_column('movies', 'original_name')
    # ### end Alembic commands ###
