"""Add push notifications table

Revision ID: f66a92f1895f
Revises: ee38ddab5497
Create Date: 2017-08-22 12:51:40.938162

"""

# revision identifiers, used by Alembic.
revision = 'f66a92f1895f'
down_revision = 'ee38ddab5497'

from alembic import op
import sqlalchemy as sa
import cineapp.migration_types



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_notifications',
    sa.Column('subscription_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('subscription_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_notifications')
    # ### end Alembic commands ###
